### ISSUE TITLE
Flying Minecarts after Serverrestart

### ISSUE THREAD

**Issue by CloudeLecaw** [TheClowner/ccRides-Support#4]
Since a few days we noticed a very stange problem.
the enabled big wheel carusell throw away the minecards and they fly in the air.
when we reload the plugin they minecarts are back on their place but a "ghostcopy" of the old minecards still fly in the air.
Some carusells seems not to be effected but most.
if the carusells are disabled before restart then there are no ghostcats.

![Snag_3fa021b](https://user-images.githubusercontent.com/12080017/87865409-3d002e00-c975-11ea-9444-0301c906fec6.png)
Here you can see some minecarts that where flying but fixed in the air and can only be removed by commands.

![Snag_3fc2c3e](https://user-images.githubusercontent.com/12080017/87865438-94060300-c975-11ea-906c-72d0635d92b2.png)
These minecarts flying until they hit a solid block, if they hit it then they move their way in the air bag

Our Server version - Paper94
if you want to see this isses your free invited to come to our server to see this issue

![Snag_4173d81](https://user-images.githubusercontent.com/12080017/87865804-b437c100-c979-11ea-8f55-826a4ed7945e.png)
Here u see our big wheel

**Comment by CloudeLecaw** [comment]
We found hout this happens ever time when a chunk is unloaded and the rides are enabled.

Now when you teleport to this chunk then you can see the minecarts fly away

So the error seems to accour with chunkloading + enabled Rides

**Comment by TheClowner** [comment]
[Fixed in v1.1.3](https://www.spigotmc.org/resources/%C2%BB-ccrides-%C2%BB-working-funfair-carnival-rides-%C2%BB-1-15-1-16-%C2%BB.80364/update?update=350016)

**Comment by Blueeyestar** [comment]
Unfortunately, the problem still exists with the new fix. Minecarts fly through the area.

**Comment by TheClowner** [comment]
Are you sure they aren't carts that were already in the world from before this update?

**Comment by Blueeyestar** [comment]
As long as you don't do an unloadchunk it works. They stay in place. So the fix helps a little

**Comment by CloudeLecaw** [comment]
i agree with that.
a good fix for that short time.
but maybe you find a little other solution later because some plugins that try to free ressouces can unload chunks automaticly.
also sometimes unloading chunks is needed ;)
But for the moment your solution from 1.1.3 works :)
